services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mobifone-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: flaskauth
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mobifone-network

  # Flask application service
  flask-app:
    build: .
    container_name: mobifone-flask-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/flaskauth
    depends_on:
      - mongodb
    networks:
      - mobifone-network
    volumes:
      - ./instance:/app/instance

volumes:
  mongodb_data:

networks:
  mobifone-network:
    driver: bridge
