services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mobifone-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: flaskauth
    ports:
      - "27018:27017"
    volumes:
      - mongodb_prod_data:/data/db
    networks:
      - mobifone-network

  # Flask application service
  flask-app:
    build: .
    container_name: mobifone-flask-app
    restart: unless-stopped
    # Port 8080 is not exposed externally, but still available to other services in the network
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/flaskauth
      - DIAGNOSTIC_API_KEY=${DIAGNOSTIC_API_KEY:-secure_diagnostic_key_123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongodb
    networks:
      - mobifone-network
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: mobifone-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/mobistt.mobifone.ai.conf:/etc/nginx/conf.d/default.conf
      - ./infrastructure/nginx/mime.types:/etc/nginx/mime.types
      - /etc/ssl/mobifone_ai.pem:/etc/ssl/mobifone_ai.pem
      - /etc/ssl/mobifone.pem:/etc/ssl/mobifone.pem
    depends_on:
      flask-app:
        condition: service_healthy
    networks:
      - mobifone-network

  # Development only: MongoDB exposed for local dev
  mongodb-dev:
    image: mongo:7.0
    container_name: mobifone-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: flaskauth
    ports:
      - "27017:27017"  # Expose default MongoDB port for local dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - mobifone-network

  # Development only: placeholder for dev mode
  dev:
    image: busybox
    container_name: mobifone-dev-placeholder
    command: tail -f /dev/null
    depends_on:
      - mongodb-dev
    networks:
      - mobifone-network
    # No ports, just a placeholder to allow `docker compose up dev` to start only db

volumes:
  mongodb_prod_data:
  mongodb_dev_data:

networks:
  mobifone-network:
    driver: bridge
